[package]
name = "twitch-emulator-04-13-24"
version = "0.1.0"
edition = "2021"
# target= "x86_64-pc-windows-msvc"
# target= "aarch64-apple-darwin"
# target= "stable-x86_64-pc-windows-gnu"


[dependencies]
enigo = "0.1.3"
tokio = { version = "1.37.0", features = ["full"] }
twitch-irc = "5.0.1"
winapi = "0.3.9"
