[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-apple]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-apple-darwin"]

[tasks.build-windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-gnu"]

[tasks.build-all]
run_task = [
    {name = ["clean", "build-apple", "build-windows"]}
]